### ISSUE TITLE
error on gulp bundle

### ISSUE THREAD

**Issue by a5m0** [stevies/berrycam-aurelia#2]
I installed nodejs with this: https://github.com/audstanley/NodeJs-Raspberry-Pi

and get this error on the gulp bundle stage:

[21:28:08] SyntaxError: src/app.html: Unexpected token (1:0)
> 1 | <template>
    | ^
  2 | 
  3 |   <div class="page-host container" id="main-container">
  4 |     <router-view></router-view>
    at Parser.pp$5.raise (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExpression (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:1906:19)
    at Parser.pp$1.parseBlockBody (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:1673:17)
    at parse (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:7246:37)
    at File.parse (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babel-core/lib/transformation/file/index.js:517:15)
    at File.parseCode (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babel-core/lib/transformation/file/index.js:602:20)
    at /home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.exports.compile (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/systemjs-builder/compilers/compiler.js:24:22)
    at Object.exports.compile (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/systemjs-builder/compilers/global.js:14:19)
    at /home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:117:43
[21:28:08] 'bundle' errored after 1.57 min
[21:28:08] SyntaxError in plugin 'run-sequence(run-bundler)'
Message:
    Error compiling global module "src/app.html" at src/app.html
        src/app.html: Unexpected token (1:0)
Details:
    pos: 0
    loc: [object Object]
    _babel: true
    codeFrame: > 1 | <template>
    | ^
  2 | 
  3 |   <div class="page-host container" id="main-container">
  4 |     <router-view></router-view>
Stack:
SyntaxError: src/app.html: Unexpected token (1:0)
> 1 | <template>
    | ^
  2 | 
  3 |   <div class="page-host container" id="main-container">
  4 |     <router-view></router-view>
    at Parser.pp$5.raise (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExpression (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:3306:19)
    at Parser.pp$1.parseStatement (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:1906:19)
    at Parser.pp$1.parseBlockBody (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:1673:17)
    at parse (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babylon/lib/index.js:7246:37)
    at File.parse (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babel-core/lib/transformation/file/index.js:517:15)
    at File.parseCode (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babel-core/lib/transformation/file/index.js:602:20)
    at /home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babel-core/lib/transformation/pipeline.js:49:12
    at File.wrap (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at Object.exports.compile (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/systemjs-builder/compilers/compiler.js:24:22)
    at Object.exports.compile (/home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/systemjs-builder/compilers/global.js:14:19)
    at /home/pi/berrycam-aurelia-v2/node_modules/jspm/node_modules/systemjs-builder/lib/compile.js:117:43

**Comment by stevies** [comment]
I have not tried a version of node since whatever was current a couple of years ago - likely v4 or earlier.
